'''
https://leetcode.com/problems/find-the-difference/
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        sDict = {}
        tDict = {}
        for char in s:
            if char not in sDict:
                sDict[char]=1
            else:
                sDict[char]+=1
        for char in t:
            if char not in tDict:
                tDict[char]=1
            else:
                tDict[char]+=1
        for key in tDict.keys():
            if key not in sDict:
                return key
            elif (tDict[key] > sDict[key]):
                return key


if __name__ == '__main__':
    print(Solution().findTheDifference('abcd', 'abcde'))

